var GrapeTreeWASMModule=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var g=moduleArg,aa=!!globalThis.window,n=!!globalThis.WorkerGlobalScope,ba=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,t="./this.program";"undefined"!=typeof __filename?_scriptName=__filename:n&&(_scriptName=self.location.href);var u="",w,y;
if(ba){var fs=require("fs");u=__dirname+"/";y=a=>{a=z(a)?new URL(a):a;return fs.readFileSync(a)};w=async a=>{a=z(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(t=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2)}else if(aa||n){try{u=(new URL(".",_scriptName)).href}catch{}n&&(y=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});w=async a=>{if(z(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;
e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var C=console.error.bind(console),D,ca=!1,z=a=>a.startsWith("file://"),da,ea,E,F,G,H,I,J,fa,ha,ja,ka,la=!1;
function ma(){var a=K.buffer;E=new Int8Array(a);G=new Int16Array(a);F=new Uint8Array(a);H=new Uint16Array(a);I=new Int32Array(a);J=new Uint32Array(a);fa=new Float32Array(a);ha=new Float64Array(a);ja=new BigInt64Array(a);ka=new BigUint64Array(a)}function L(a){g.onAbort?.(a);a="Aborted("+a+")";C(a);ca=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ea?.(a);throw a;}var M;
async function na(a){if(!D)try{var b=await w(a);return new Uint8Array(b)}catch{}if(a==M&&D)a=new Uint8Array(D);else if(y)a=y(a);else throw"both async and sync fetching of the wasm failed";return a}async function oa(a,b){try{var c=await na(a);return await WebAssembly.instantiate(c,b)}catch(d){C(`failed to asynchronously prepare wasm: ${d}`),L(d)}}
async function pa(a){var b=M;if(!D&&!z(b)&&!ba)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){C(`wasm streaming compile failed: ${d}`),C("falling back to ArrayBuffer instantiation")}return oa(b,a)}
var qa=a=>{for(;0<a.length;)a.shift()(g)},ra=[],sa=[],ta=()=>{var a=g.preRun.shift();sa.push(a)},ua=globalThis.TextDecoder&&new TextDecoder,va=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},O=(a=0,b,c)=>{var d=F;b=va(d,a,b,c);if(16<b-a&&d.buffer&&ua)return ua.decode(d.subarray(a,b));for(c="";a<b;){var e=d[a++];if(e&128){var f=d[a++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var h=d[a++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|d[a++]&63;65536>e?
c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c};class wa{constructor(a){this.J=a-24}}var xa=0,ya=0,P=a=>{for(var b="";;){var c=F[a++];if(!c)return b;b+=String.fromCharCode(c)}},Q={},R={},S={},T=class extends Error{constructor(a){super(a);this.name="BindingError"}},za=a=>{throw new T(a);};
function Aa(a,b,c={}){var d=b.name;if(!a)throw new T(`type "${d}" must have a positive integer typeid pointer`);if(R.hasOwnProperty(a)){if(c.N)return;throw new T(`Cannot register type '${d}' twice`);}R[a]=b;delete S[a];Q.hasOwnProperty(a)&&(b=Q[a],delete Q[a],b.forEach(e=>e()))}function U(a,b,c={}){return Aa(a,b,c)}
var Ba=(a,b,c)=>{switch(b){case 1:return c?d=>E[d]:d=>F[d];case 2:return c?d=>G[d>>1]:d=>H[d>>1];case 4:return c?d=>I[d>>2]:d=>J[d>>2];case 8:return c?d=>ja[d>>3]:d=>ka[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ca=[],V=[0,1,,1,null,1,!0,1,!1,1],Da=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Ca.pop()||V.length;V[b]=a;V[b+1]=1;return b}};function Ea(a){return this.C(J[a>>2])}
var Fa={name:"emscripten::val",C:a=>{if(!a)throw new T(`Cannot use deleted val. handle = ${a}`);var b=V[a];9<a&&0===--V[a+1]&&(V[a]=void 0,Ca.push(a));return b},F:(a,b)=>Da(b),H:Ea,D:null},Ga=(a,b)=>{if(void 0===g[a].G){var c=g[a];g[a]=function(...d){if(!g[a].G.hasOwnProperty(d.length))throw new T(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${g[a].G})!`);return g[a].G[d.length].apply(this,d)};g[a].G=[];g[a].G[c.I]=c}},W=(a,b,c)=>{if(g.hasOwnProperty(a)){if(void 0===
c||void 0!==g[a].G&&void 0!==g[a].G[c])throw new T(`Cannot register public name '${a}' twice`);Ga(a,a);if(g[a].G.hasOwnProperty(c))throw new T(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);g[a].G[c]=b}else g[a]=b,g[a].I=c},Ha=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.C(E[d])}:function(d){return this.C(F[d])};case 2:return c?function(d){return this.C(G[d>>1])}:function(d){return this.C(H[d>>1])};case 4:return c?function(d){return this.C(I[d>>
2])}:function(d){return this.C(J[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ia=(a,b)=>Object.defineProperty(b,"name",{value:a}),Ka=a=>{a=Ja(a);var b=P(a);X(a);return b},La=a=>{var b=R[a];if(void 0===b)throw a=`${"enum"} has unknown type ${Ka(a)}`,new T(a);return b},Pa=(a,b)=>{switch(b){case 4:return function(c){return this.C(fa[c>>2])};case 8:return function(c){return this.C(ha[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Qa=a=>{for(;a.length;){var b=
a.pop();a.pop()(b)}};function Ra(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].D)return!0;return!1}var Sa=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(J[b+4*d>>2]);return c},Ta=class extends Error{constructor(a){super(a);this.name="InternalError"}},Va=(a,b)=>{a=P(a);var c=Ua.get(b);if("function"!=typeof c)throw new T(`unknown function pointer with signature ${a}: ${b}`);return c};class Wa extends Error{}
var Xa=(a,b)=>{function c(f){e[f]||R[f]||(S[f]?S[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Wa(`${a}: `+d.map(Ka).join([", "]));},Ya=(a,b)=>{function c(k){k=b(k);if(k.length!==d.length)throw new Ta("Mismatched type converter count");for(var m=0;m<d.length;++m)U(d[m],k[m])}var d=[];d.forEach(k=>S[k]=a);var e=Array(a.length),f=[],h=0;for(let [k,m]of a.entries())R.hasOwnProperty(m)?e[k]=R[m]:(f.push(m),Q.hasOwnProperty(m)||(Q[m]=[]),Q[m].push(()=>{e[k]=R[m];++h;h===f.length&&
c(e)}));0===f.length&&c(e)},Za=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Y=(a,b,c)=>{var d=F;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var h=a.codePointAt(f);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;f++}}d[b]=0;return b-
e},$a=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},ab=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,bb=(a,b,c)=>{a>>=1;b=va(H,a,b/2,c);if(16<b-a&&ab)return ab.decode(H.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(H[a]);return c},cb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)G[b>>1]=a.charCodeAt(e),b+=2;G[b>>1]=0;return b-d},db=a=>2*a.length,
eb=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=J[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},fb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;I[b>>2]=f;b+=4;if(b+4>c)break}I[b>>2]=0;return b-d},gb=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},hb={},jb=()=>{if(!ib){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??
"C").replace("-","_")+".UTF-8",_:t||"./this.program"},b;for(b in hb)void 0===hb[b]?delete a[b]:a[b]=hb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);ib=c}return ib},ib,nb=(a,b,c,d)=>{var e={string:l=>{var q=0;if(null!==l&&void 0!==l&&0!==l){q=$a(l)+1;var A=kb(q);Y(l,A,q);q=A}return q},array:l=>{var q=kb(l.length);E.set(l,q);return q}};a=g["_"+a];var f=[],h=0;if(d)for(var k=0;k<d.length;k++){var m=e[c[k]];m?(0===h&&(h=lb()),f[k]=m(d[k])):f[k]=d[k]}c=a(...f);return c=function(l){0!==h&&mb(h);return"string"===
b?l?O(l):"":"boolean"===b?!!l:l}(c)};g.printErr&&(C=g.printErr);g.wasmBinary&&(D=g.wasmBinary);g.thisProgram&&(t=g.thisProgram);if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.shift()();g.ccall=nb;g.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?g["_"+a]:(...f)=>nb(a,b,c,f,d)};
var Ja,ob,X,mb,kb,lb,K,Ua,pb={a:(a,b,c,d)=>L(`Assertion failed: ${a?O(a):""}, at: `+[b?b?O(b):"":"unknown filename",c,d?d?O(d):"":"unknown function"]),c:(a,b,c)=>{var d=new wa(a);J[d.J+16>>2]=0;J[d.J+4>>2]=b;J[d.J+8>>2]=c;xa=a;ya++;throw xa;},p:()=>L(""),h:(a,b,c,d,e)=>{b=P(b);d=0n===d;let f=h=>h;if(d){const h=8*c;f=k=>BigInt.asUintN(h,k);e=f(e)}U(a,{name:b,C:f,F:(h,k)=>{"number"==typeof k&&(k=BigInt(k));return k},H:Ba(b,c,!d),D:null})},k:(a,b,c,d)=>{b=P(b);U(a,{name:b,C:function(e){return!!e},F:function(e,
f){return f?c:d},H:function(e){return this.C(F[e])},D:null})},r:a=>U(a,Fa),i:(a,b,c,d,e)=>{b=P(b);e=0===e?"object":1===e?"number":"string";switch(e){case "object":function h(){}h.values={};U(a,{name:b,constructor:h,valueType:e,C:function(k){return this.constructor.values[k]},F:(k,m)=>m.value,H:Ha(b,c,d),D:null});W(b,h);break;case "number":var f={};U(a,{name:b,K:f,valueType:e,C:k=>k,F:(k,m)=>m,H:Ha(b,c,d),D:null});W(b,f);delete g[b].I;break;case "string":f={},U(a,{name:b,M:{},L:{},K:f,valueType:e,
C:function(k){return this.L[k]},F:function(k,m){return this.M[m]},H:Ha(b,c,d),D:null}),W(b,f),delete g[b].I}},e:(a,b,c)=>{var d=La(a);b=P(b);switch(d.valueType){case "object":a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Ia(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d;break;case "number":d.K[b]=c;break;case "string":d.M[b]=c,d.L[c]=b,d.K[b]=b}},g:(a,b,c)=>{b=P(b);U(a,{name:b,C:d=>d,F:(d,e)=>e,H:Pa(b,c),D:null})},j:(a,b,c,d,e,f,h)=>{var k=Sa(b,
c);a=P(a);a=Za(a);e=Va(d,e);W(a,function(){Xa(`Cannot call ${a} due to unbound types`,k)},b-1);Ya(k,m=>{var l=[m[0],null].concat(m.slice(1));m=a;var q=a;var A=e,p=l.length;if(2>p)throw new T("argTypes array size mismatch! Must at least get return value and 'this' types!");var B=null!==l[1]&&!1,N=Ra(l),Ma=!l[0].O,r=l[0],x=l[1];A=[q,za,A,f,Qa,r.C.bind(r),x?.F.bind(x)];for(r=2;r<p;++r)x=l[r],A.push(x.F.bind(x));if(!N)for(r=B?1:2;r<l.length;++r)null!==l[r].D&&A.push(l[r].D);N=Ra(l);r=l.length-2;var v=
[];x=["fn"];B&&x.push("thisWired");for(p=0;p<r;++p)v.push(`arg${p}`),x.push(`arg${p}Wired`);v=v.join(",");x=x.join(",");v=`return function (${v}) {\n`;N&&(v+="var destructors = [];\n");var Na=N?"destructors":"null",ia="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");B&&(v+=`var thisWired = toClassParamWire(${Na}, this);\n`);for(p=0;p<r;++p){var Oa=`toArg${p}Wire`;v+=`var arg${p}Wired = ${Oa}(${Na}, arg${p});\n`;ia.push(Oa)}v+=(Ma||h?"var rv = ":"")+`invoker(${x});\n`;
if(N)v+="runDestructors(destructors);\n";else for(p=B?1:2;p<l.length;++p)B=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==l[p].D&&(v+=`${B}_dtor(${B});\n`,ia.push(`${B}_dtor`));Ma&&(v+="var ret = fromRetWire(rv);\nreturn ret;\n");l=(new Function(ia,v+"}\n"))(...A);q=Ia(q,l);l=b-1;if(!g.hasOwnProperty(m))throw new Ta("Replacing nonexistent public symbol");void 0!==g[m].G&&void 0!==l?g[m].G[l]=q:(g[m]=q,g[m].I=l);return[]})},d:(a,b,c,d,e)=>{b=P(b);let f=k=>k;if(0===d){var h=32-8*c;f=k=>k<<h>>>h;e=f(e)}U(a,
{name:b,C:f,F:(k,m)=>m,H:Ba(b,c,0!==d),D:null})},b:(a,b,c)=>{function d(f){return new e(E.buffer,J[f+4>>2],J[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=P(c);U(a,{name:c,C:d,H:d},{N:!0})},s:(a,b)=>{b=P(b);U(a,{name:b,C(c){var d=(d=c+4)?O(d,J[c>>2],!0):"";X(c);return d},F(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new T("Cannot pass non-string to std::string");
var f=e?$a(d):d.length;var h=ob(4+f+1),k=h+4;J[h>>2]=f;e?Y(d,k,f+1):F.set(d,k);null!==c&&c.push(X,h);return h},H:Ea,D(c){X(c)}})},f:(a,b,c)=>{c=P(c);if(2===b){var d=bb;var e=cb;var f=db}else d=eb,e=fb,f=gb;U(a,{name:c,C:h=>{var k=d(h+4,J[h>>2]*b,!0);X(h);return k},F:(h,k)=>{if("string"!=typeof k)throw new T(`Cannot pass non-string to C++ string type ${c}`);var m=f(k),l=ob(4+m+b);J[l>>2]=m/b;e(k,l+4,m+b);null!==h&&h.push(X,l);return l},H:Ea,D(h){X(h)}})},l:(a,b)=>{b=P(b);U(a,{O:!0,name:b,C:()=>{},
F:()=>{}})},m:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();J[a>>2]=60*Math.max(f,e);I[b>>2]=Number(f!=e);b=h=>{var k=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(Y(a,c,17),Y(b,d,17)):(Y(a,d,17),Y(b,c,17))},q:a=>{var b=F.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,
65536*Math.ceil(Math.max(a,d)/65536))-K.buffer.byteLength+65535)/65536|0;try{K.grow(d);ma();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},n:(a,b)=>{var c=0,d=0,e;for(e of jb()){var f=b+c;J[a+d>>2]=f;c+=Y(e,f,Infinity)+1;d+=4}return 0},o:(a,b)=>{var c=jb();J[a>>2]=c.length;a=0;for(var d of c)a+=$a(d)+1;J[b>>2]=a;return 0}},Z;
Z=await (async function(){function a(c){c=Z=c.exports;Ja=c.v;ob=c.x;X=c.y;mb=c.z;kb=c.A;lb=c.B;K=c.t;Ua=c.w;ma();return Z}var b={a:pb};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{c(a(d,e))})});M??=g.locateFile?g.locateFile("grapetree.wasm",u):u+"grapetree.wasm";return a((await pa(b)).instance)}());
(function(){function a(){g.calledRun=!0;if(!ca){la=!0;Z.u();da?.(g);g.onRuntimeInitialized?.();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();ra.push(b)}qa(ra)}}if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)ta();qa(sa);g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);a()},1)):a()})();la?moduleRtn=g:moduleRtn=new Promise((a,b)=>{da=a;ea=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=GrapeTreeWASMModule;module.exports.default=GrapeTreeWASMModule}else if(typeof define==="function"&&define["amd"])define([],()=>GrapeTreeWASMModule);
